
const DUPLICATED_ARTIST_ERROR = 'DuplicatedArtist';
const ARTIST_DOESNT_EXIST_ERROR = 'ArtistDoesNotExist';
const ALBUM_CANT_BE_CREATED_ERROR = 'AlbumCantBeCreated';
const DUPLICATED_ALBUM_ERROR = 'DuplicatedAlbum';
const ALBUM_DOESNT_EXIST_ERROR = 'AlbumDoesNotExist';
const TRACK_DOESNT_EXIST_ERROR = 'TrackDoesNotExist';
const PLAYLIST_DOESNT_EXIST_ERROR = 'PlaylistDoesNotExist';

module.exports={
  DUPLICATED_ARTIST_ERROR,
  DUPLICATED_ALBUM_ERROR,
  ARTIST_DOESNT_EXIST_ERROR,
  ALBUM_CANT_BE_CREATED_ERROR,
  ALBUM_DOESNT_EXIST_ERROR,
  TRACK_DOESNT_EXIST_ERROR,
  PLAYLIST_DOESNT_EXIST_ERROR};